### ISSUE TITLE
RFSoC 2x2 Backend compile issue - missing tile228?

### ISSUE THREAD

**Issue by harshadms** [casper-astro/mlib_devel#204]
Hi, I'm trying to set up a toolflow for working with an RFSoC 2x2 board (I'm extremely new to FPGA programming). I understand the general flow of operations. I tried the first tutorial, and I could build and load the FPGA bitstream, and everything worked fine. Now I'm on tutorial two and having issues during backend compilation, specifically while generating the RFDC yellow block. 
Posting the error message here.
```
grabbing data from yaml, this is a gen 1 part
Traceback (most recent call last):
  File "/home/harshad/Tools/rfsoc/mlib_devel/jasper_library/exec_flow.py", line 209, in <module>
    tf.gen_periph_objs()
  File "/home/harshad/Tools/rfsoc/mlib_devel/jasper_library/toolflow.py", line 415, in gen_periph_objs
    self.periph_objs.append(yellow_block.YellowBlock.make_block(
  File "/home/harshad/Tools/rfsoc/mlib_devel/jasper_library/yellow_blocks/yellow_block.py", line 65, in make_block
    return cls(blk,platform,hdl_root=hdl_root)
  File "/home/harshad/Tools/rfsoc/mlib_devel/jasper_library/yellow_blocks/yellow_block.py", line 152, in __init__
    self.initialize()
  File "/home/harshad/Tools/rfsoc/mlib_devel/jasper_library/yellow_blocks/rfdc.py", line 273, in initialize
    t.has_clk_src = self.rfdc_conf['tile{:d}'.format(tidx)]['has_dac_clk']
KeyError: 'tile228'
```

I checked the .yaml file for rfsoc 2x2 and I noticed that config for tiles 228 - 231 are missing and rfdc.py is trying to build objects for DAC tiles. I'm not sure how it is supposed to behave in this scenario. 

I did try the provided tutorial model (rfsoc2x2_tut_rfdc.slx). I had to reset clk values to get rid of incompatible clk rate errors. Please let me know if you want some information.

Any help would be appreciated!

**Comment by mitchburnett** [comment]
The `rfsoc2x2` was ported prior to formal DAC support in the RFDC yellow block. Then as support for the DAC emerged various platforms got out of sync with the rest of the project. This should be fixed with #205 shortly to merge.
